import http from 'node:http';
import net from 'node:net';
import os from 'node:os';
import crypto from 'node:crypto';

const PORT=Number(process.env.FINGERPRINT_GATEWAY_PORT||8787);
const HOST=process.env.FINGERPRINT_GATEWAY_HOST||'0.0.0.0';
const ZK_USERS=Buffer.from([0x01,0x09,0x00,0x05,0x00,0x00,0x00,0x00,0x00,0x00,0x00]);

function clean(v){return String(v??'').replace(/\u0000/g,'').trim();}
function arabicCount(v){return (String(v).match(/[\u0600-\u06ff]/g)||[]).length;}
function printableCount(v){return (String(v).match(/[\x20-\x7e\u0600-\u06ff]/g)||[]).length;}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',x=>s+=x);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject);});}
function localSubnets(){const out=[];for(const list of Object.values(os.networkInterfaces()))for(const n of list||[])if(!n.internal&&n.family==='IPv4')out.push(n.address.split('.').slice(0,3).join('.'));return [...new Set(out)];}
function tcpOpen(ip,port,timeout=1000){return new Promise(resolve=>{const s=new net.Socket();let done=false;const finish=v=>{if(done)return;done=true;s.destroy();resolve(v)};s.setTimeout(timeout);s.once('connect',()=>finish(true));s.once('timeout',()=>finish(false));s.once('error',()=>finish(false));s.connect(Number(port),ip);});}
async function discover(onlyPort){const ports=onlyPort?[Number(onlyPort)]:[4370,80,443,8000,8080,8081,8443,9000,37777],found=[];for(const subnet of localSubnets()){const jobs=[];for(let h=1;h<=254;h++)for(const port of ports)jobs.push(tcpOpen(`${subnet}.${h}`,port,700).then(ok=>ok?{ip:`${subnet}.${h}`,port}:null));for(let i=0;i<jobs.length;i+=80)found.push(...(await Promise.all(jobs.slice(i,i+80))).filter(Boolean));}const m=new Map();for(const x of found){const k=`${x.ip}|${x.port}`;if(!m.has(k))m.set(k,{...x,protocol:x.port===4370?'zk':x.port===8000?'hikvision':'http',name:x.port===4370?'ZKTeco / ZK-compatible biometric device':x.port===8000?'Hikvision candidate':'HTTP biometric device',source:'LAN TCP discovery'});}return [...m.values()];}
function decodeZkField(buf){const raw=Buffer.from(buf),end=raw.indexOf(0),b=end>=0?raw.subarray(0,end):raw;if(!b.length)return '';const a=[];const add=(label,text)=>{text=clean(text);if(text)a.push({label,text})};add('utf8',b.toString('utf8'));add('utf16le',b.toString('utf16le'));try{add('windows-1256',new TextDecoder('windows-1256').decode(b))}catch{}add('latin1',b.toString('latin1'));add('ascii',b.toString('ascii'));return a.sort((x,y)=>(arabicCount(y.text)*100+printableCount(y.text))-(arabicCount(x.text)*100+printableCount(x.text)))[0]?.text||'';}
function parseRawUsers(data){const b=Buffer.from(data);let p=0;if(b.length>=4){const n=b.readUInt32LE(0);if(n>0&&n<=b.length-4)p=4;}const out=[];for(;p+72<=b.length;p+=72){const r=b.subarray(p,p+72),uid=r.readUInt16LE(0),name=decodeZkField(r.subarray(11,35)),cardno=String(r.readUInt32LE(35)),userId=decodeZkField(r.subarray(48,57));if(uid||name||userId)out.push({uid,name,cardno,userId});}return out;}
async function openZk(d){let Zkteco;try{({default:Zkteco}=await import('zkteco-js'))}catch{throw new Error('Driver zkteco-js غير مثبت داخل admin-affairs.')}const device=new Zkteco(d.ip,Number(d.port)||4370,10000,10000);await device.createSocket();return device;}
function unwrapSdk(r){return Array.isArray(r)?r:(r?.data||r?.users||r?.logs||r?.records||[])}
function sdkUser(r){return {pin:clean(r?.userid??r?.userId??r?.user_id??r?.pin??r?.id),uid:String(r?.uid??r?.userSn??''),name:clean(r?.name??r?.userName??r?.username),card:String(r?.cardno??r?.cardNo??r?.card??'0')}}
function sdkLog(r){const userId=clean(r?.userid??r?.userId??r?.user_id??r?.pin??r?.deviceUserId??r?.device_user_id),rawDate=r?.recordTime??r?.record_time??r?.attTime??r?.timestamp??r?.time??r?.datetime,d=rawDate instanceof Date?rawDate:new Date(rawDate);return userId&&!Number.isNaN(d.getTime())?{userId,timestamp:d}:null;}
async function pullZkUsers(d){const device=await openZk(d);try{return unwrapSdk(await device.getUsers()).map(sdkUser).filter(x=>x.pin||x.name)}finally{try{await device.disconnect()}catch{}}}
async function pullZk(d){const device=await openZk(d);try{const users=unwrapSdk(await device.getUsers()).map(sdkUser),logs=unwrapSdk(await device.getAttendances()).map(sdkLog).filter(Boolean),byPin=new Map(users.filter(x=>x.pin).map(x=>[clean(x.pin),x]));return logs.map(x=>{const u=byPin.get(clean(x.userId)),code=clean(u?.pin)||clean(x.userId);if(!code)return null;return {id:Date.now()+Math.floor(Math.random()*100000),code,name:clean(u?.name),date:x.timestamp.toISOString().slice(0,10),time:x.timestamp.toTimeString().slice(0,5)}}).filter(Boolean)}finally{try{await device.disconnect()}catch{}}}
async function testZk(d){try{const device=await openZk(d);try{const users=unwrapSdk(await device.getUsers()).map(sdkUser);return {ok:true,message:`تم الاتصال بنجاح وقراءة ${users.length} مستخدم من جهاز البصمة.`}}finally{try{await device.disconnect()}catch{}}}catch(e){return {ok:false,message:'فشل اتصال ZKTeco: '+(e instanceof Error?e.message:String(e))}}}
async function pullHik(d){const auth=Buffer.from(`${d.username||''}:${d.password||''}`).toString('base64'),now=new Date(),start=new Date(now.getTime()-7*86400000),url=`http://${d.ip}:${Number(d.port)||80}/ISAPI/AccessControl/AcsEvent?format=json`,payload={AcsEventCond:{searchID:crypto.randomUUID(),searchResultPosition:0,maxResults:1000,major:5,minor:0,startTime:start.toISOString(),endTime:now.toISOString()}},r=await fetch(url,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`Hikvision HTTP ${r.status}`);const j=await r.json(),list=j?.AcsEvent?.InfoList||j?.AcsEvent?.AcsEventInfo||[];return (Array.isArray(list)?list:[list]).map(x=>{const code=clean(x.employeeNoString??x.employeeNo),d=new Date(x.time||x.dateTime||'');return !code||Number.isNaN(d.getTime())?null:{id:Date.now()+Math.floor(Math.random()*100000),code,name:clean(x.name),date:d.toISOString().slice(0,10),time:d.toTimeString().slice(0,5)}}).filter(Boolean);}
async function pullGenericHttp(d){const protocol=Number(d.port)===443||Number(d.port)===8443?'https':'http',base=`${protocol}://${d.ip}:${Number(d.port)||80}`,paths=['/api/attendance','/api/records','/ISAPI/AccessControl/AcsEvent'],auth=d.username?Buffer.from(`${d.username}:${d.password||''}`).toString('base64'):'';for(const path of paths)try{const r=await fetch(base+path,{headers:auth?{Authorization:`Basic ${auth}`}:{}});if(!r.ok)continue;const j=await r.json(),list=j.records||j.data||j.Attendance||j.AcsEvent?.InfoList||[];if(!Array.isArray(list))continue;return list.map(x=>{const code=clean(x.code??x.pin??x.user_id??x.employeeNoString??x.employeeNo),d=new Date(x.datetime??x.timestamp??x.time??x.dateTime??'');return !code||Number.isNaN(d.getTime())?null:{id:Date.now()+Math.floor(Math.random()*100000),code,name:clean(x.name??x.user_name),date:d.toISOString().slice(0,10),time:d.toTimeString().slice(0,5)}}).filter(Boolean)}catch{}throw new Error('لم يتم التعرف على API قياسي لهذا الجهاز.');}
async function testDevice(d){if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370))return testZk(d);const ok=await tcpOpen(d.ip,Number(d.port)||80,1200);return {ok,message:ok?'منفذ الجهاز متاح.':'منفذ الجهاز غير متاح.'};}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS')return json(res,204,{});if(u.pathname==='/api/fingerprint/health')return json(res,200,{ok:true,port:PORT});if(u.pathname==='/api/fingerprint/discover')return json(res,200,{devices:await discover(u.searchParams.get('port'))});if(u.pathname==='/api/fingerprint/test'){const r=await testDevice({ip:u.searchParams.get('ip'),port:Number(u.searchParams.get('port')||4370),protocol:u.searchParams.get('protocol')||'auto'});return json(res,r.ok?200:502,r)}if(u.pathname==='/api/fingerprint/users'&&req.method==='POST'){const d=await body(req);if(!d?.ip)throw new Error('عنوان جهاز البصمة مطلوب.');if(d.protocol==='zk'||d.protocol==='auto')return json(res,200,{users:await pullZkUsers(d)});throw new Error('استيراد المستخدمين متاح حاليًا لأجهزة ZKTeco.')}if(u.pathname==='/api/fingerprint/pull'&&req.method==='POST'){const d=await body(req);let punches=[];if(d.protocol==='zk'||(d.protocol==='auto'&&Number(d.port)===4370))punches=await pullZk(d);else if(d.protocol==='hikvision')punches=await pullHik(d);else if(d.protocol==='http'||d.protocol==='auto')punches=await pullGenericHttp(d);else throw new Error('لا يوجد Driver لهذا البروتوكول حتى الآن.');return json(res,200,{punches,count:punches.length})}return json(res,404,{message:'Not found'})}catch(e){return json(res,500,{ok:false,message:e instanceof Error?e.message:String(e)})}});
server.listen(PORT,HOST,()=>console.log(`Fingerprint Gateway listening on http://${HOST}:${PORT}`));
