import { useMemo, useState } from 'react'
type Employee={id:number;code:string;name:string;department:string;job:string;status:string}
type Punch={id:number;code:string;name:string;date:string;time:string}
type Leave={id:number;employeeId:number;type:string;from:string;to:string;days:number;status:string;note:string}
type MedicalLeave={id:number;employeeId:number;from:string;to:string;days:number;reason:string;status:string}
type Mission={id:number;employeeId:number;from:string;to:string;destination:string;purpose:string;status:string}
type Exception={id:number;employeeId:number;date:string;type:string;note:string;source:string}
type Balance={employeeId:number;year:string;annual:number;casual:number}
type Section='dashboard'|'employees'|'attendance'|'leaves'|'medical'|'missions'|'shifts'|'forms'|'reports'|'fingerprints'|'settings'
const today=()=>new Date().toISOString().slice(0,10),uid=()=>Date.now()+Math.floor(Math.random()*1000)
const days=(a:string,b:string)=>Math.max(1,Math.floor((new Date(b+'T00:00:00').getTime()-new Date(a+'T00:00:00').getTime())/86400000)+1)
export default function DashboardEnhanced({employees,punches,leaves,missions,medicalLeaves,exceptions,balances,settings,go,setLeaves,setMissions,setMedicalLeaves}:{employees:Employee[];punches:Punch[];leaves:Leave[];missions:Mission[];medicalLeaves:MedicalLeave[];exceptions:Exception[];balances:Balance[];settings:any;go:(s:Section)=>void;setLeaves:any;setMissions:any;setMedicalLeaves:any}){
 const d=today(),[open,setOpen]=useState(''),[q,setQ]=useState('')
 const isCollector=(e:Employee)=>/محصل/i.test(e.job||''),isCouncil=(e:Employee)=>/فني|فنى/.test(e.job||'')||/فني|فنى/.test(e.department||''),collectorDay=[0,2,4].includes(new Date(d+'T00:00:00').getDay()),isFriday=new Date(d+'T00:00:00').getDay()===5
 const isLeave=(e:Employee)=>leaves.some(x=>x.employeeId===e.id&&x.status==='معتمدة'&&d>=x.from&&d<=x.to),isSick=(e:Employee)=>medicalLeaves.some(x=>x.employeeId===e.id&&x.status!=='مرفوض'&&d>=x.from&&d<=x.to),isMission=(e:Employee)=>missions.some(x=>x.employeeId===e.id&&x.status==='معتمدة'&&d>=x.from&&d<=x.to)
 const expected=useMemo(()=>employees.filter(e=>{if(isFriday&&settings.fridayOff)return false;if(String(settings.holidays||'').split(/[\n,;]+/).map((x:string)=>x.trim()).includes(d))return false;if(isLeave(e)||isSick(e)||isMission(e))return false;if(isCollector(e))return collectorDay; if(isCouncil(e))return true; return true}),[employees,punches,leaves,missions,medicalLeaves,d,settings])
 const unresolved=expected.filter(e=>!punches.some(p=>p.code===e.code&&p.date===d)&&!exceptions.some(x=>x.employeeId===e.id&&x.date===d&&x.type!=='غياب'))
 const todayLeaves=leaves.filter(x=>x.status==='معتمدة'&&d>=x.from&&d<=x.to),annual=todayLeaves.filter(x=>x.type==='اعتيادية').length,casual=todayLeaves.filter(x=>x.type==='عارضة').length,sick=medicalLeaves.filter(x=>x.status!=='مرفوض'&&d>=x.from&&d<=x.to).length,missionsToday=missions.filter(x=>x.status==='معتمدة'&&d>=x.from&&d<=x.to).length
 const unsolved=unresolved.length
 const rows=useMemo(()=>{const source=open==='غياب'?unresolved:open==='اعتيادي'?todayLeaves.filter(x=>x.type==='اعتيادية').map(x=>employees.find(e=>e.id===x.employeeId)).filter(Boolean) as Employee[]:open==='عارضة'?todayLeaves.filter(x=>x.type==='عارضة').map(x=>employees.find(e=>e.id===x.employeeId)).filter(Boolean) as Employee[]:open==='مرضي'?medicalLeaves.filter(x=>x.status!=='مرفوض'&&d>=x.from&&d<=x.to).map(x=>employees.find(e=>e.id===x.employeeId)).filter(Boolean) as Employee[]:missions.filter(x=>x.status==='معتمدة'&&d>=x.from&&d<=x.to).map(x=>employees.find(e=>e.id===x.employeeId)).filter(Boolean) as Employee[];return source.filter(e=>(e.name+' '+e.code).includes(q))},[open,unresolved,todayLeaves,medicalLeaves,missions,employees,q,d])
 function settle(e:Employee,type:string){if(type==='اعتيادي'||type==='عارضة'){const y=d.slice(0,4),b=balances.find(x=>x.employeeId===e.id&&x.year===y)||{employeeId:e.id,year:y,annual:30,casual:7},leaveType=type==='اعتيادي'?'اعتيادية':'عارضة',used=leaves.filter(x=>x.employeeId===e.id&&x.status==='معتمدة'&&x.type===leaveType).reduce((n,x)=>n+days(x.from,x.to),0),available=(type==='اعتيادي'?b.annual:b.casual)-used;if(available<1&&!confirm('الرصيد غير كافٍ، هل تريد التسوية رغم ذلك؟'))return;setLeaves((xs:Leave[])=>[...xs,{id:uid(),employeeId:e.id,type:leaveType,from:d,to:d,days:1,status:'معتمدة',note:'تسوية غياب من الرئيسية'}])}else if(type==='مأمورية')setMissions((xs:Mission[])=>[...xs,{id:uid(),employeeId:e.id,from:d,to:d,destination:'—',purpose:'مأمورية',status:'معتمدة'}]);else if(type==='مرضي')setMedicalLeaves((xs:MedicalLeave[])=>[...xs,{id:uid(),employeeId:e.id,from:d,to:d,days:1,reason:'مرضي',status:'معتمد'}]);setOpen('')}
 const cards=[['غياب غير مسوى',unsolved,'غياب'],['اعتيادي',annual,'اعتيادي'],['عارضة',casual,'عارضة'],['مرضي',sick,'مرضي'],['مأمورية',missionsToday,'مأمورية']]
 return <><section className="dashboard-settlement"><div className="dashboard-settlement-head"><div><h2>التسوية اليومية</h2><p>{d} — اضغط على أي رقم لعرض الموظفين والتسوية مباشرة.</p></div><button className="view-btn" onClick={()=>go('reports')}>📊 فتح التقارير</button></div><div className="settlement-grid">{cards.map(c=><button key={String(c[2])} className={'settlement-card '+(c[2]==='غياب'?'danger':'')} onClick={()=>setOpen(String(c[2]))}><span>{c[0]}</span><strong>{c[1]}</strong><small>عرض التفاصيل</small></button>)}</div></section>{open&&<div className="modal-backdrop"><div className="modal wide-modal"><div className="modal-head"><h2>تفاصيل {open} — {d}</h2><button onClick={()=>setOpen('')}>×</button></div><input className="profile-search" placeholder="ابحث بالاسم أو الكود..." value={q} onChange={e=>setQ(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>الكود</th><th>الوظيفة</th><th>الحالة</th><th>التسوية</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.code}</td><td>{e.job||'—'}</td><td>{open==='غياب'?'غير مسوى':'مسجل'}</td><td>{open==='غياب'?<div className="actions"><button className="view-btn" onClick={()=>settle(e,'اعتيادي')}>اعتيادي</button><button className="view-btn" onClick={()=>settle(e,'عارضة')}>عارضة</button><button className="view-btn" onClick={()=>settle(e,'مأمورية')}>مأمورية</button><button className="view-btn" onClick={()=>settle(e,'مرضي')}>مرضي</button></div>:<span className="badge">تم التسجيل</span>}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>لا توجد حالات.</td></tr>}</tbody></table></div></div></div>}{false&&<div/>}</>
}
