import { useState } from 'react'
import type { Dispatch, SetStateAction } from 'react'
type Employee={id:number;code:string;name:string;department:string;job:string;grade?:string;phone:string;status:string;nationalId?:string}
type MedicalFile={id:number;employeeId:number;diagnosis:string;doctor:string;hospital:string;notes:string}
type MedicalExam={id:number;employeeId:number;date:string;type:string;result:string;doctor:string}
type MedicalLeave={id:number;employeeId:number;from:string;to:string;days:number;reason:string;status:string}
type TreatmentRequest={id:number;employeeId:number;date:string;medicine:string;quantity:string;status:string;notes:string;provider?:string}
type TreatmentDecision={id:number;employeeId:number;decisionNo:string;issueDate:string;startDate:string;endDate:string;renewalMonths:number;monthlyTreatment:string;status:string;notes:string;previousDecisionId?:number}
type InsuranceRecord={id:number;employeeId:number;provider:string;policyNo:string;from:string;to:string;notes:string}
type TreatmentDispense={id:number;decisionId:number;employeeId:number;month:string;dispenseDate:string;medicine:string;quantity:string;status:string;notes:string}
const uid=()=>Date.now()+Math.floor(Math.random()*1000),today=()=>new Date().toISOString().slice(0,10),days=(a:string,b:string)=>Math.max(1,Math.floor((new Date(b+'T00:00:00').getTime()-new Date(a+'T00:00:00').getTime())/86400000)+1)
export default function MedicalEnhanced({employees,medicalFiles,setMedicalFiles,medicalExams,setMedicalExams,medicalLeaves,setMedicalLeaves,treatmentRequests,setTreatmentRequests,treatmentDecisions,setTreatmentDecisions,treatmentDispenses,setTreatmentDispenses,insurance,setInsurance}:{employees:Employee[];medicalFiles:MedicalFile[];setMedicalFiles:Dispatch<SetStateAction<MedicalFile[]>>;medicalExams:MedicalExam[];setMedicalExams:Dispatch<SetStateAction<MedicalExam[]>>;medicalLeaves:MedicalLeave[];setMedicalLeaves:Dispatch<SetStateAction<MedicalLeave[]>>;treatmentRequests:TreatmentRequest[];setTreatmentRequests:Dispatch<SetStateAction<TreatmentRequest[]>>;treatmentDecisions:TreatmentDecision[];setTreatmentDecisions:Dispatch<SetStateAction<TreatmentDecision[]>>;treatmentDispenses:TreatmentDispense[];setTreatmentDispenses:Dispatch<SetStateAction<TreatmentDispense[]>>;insurance:InsuranceRecord[];setInsurance:Dispatch<SetStateAction<InsuranceRecord[]>>}){
 const [tab,setTab]=useState('overview'),[open,setOpen]=useState(''),[preview,setPreview]=useState<TreatmentRequest|null>(null)
 const [form,setForm]=useState({employeeId:employees[0]?.id||0,date:today(),medicine:'',quantity:'',notes:'',provider:'',status:'جديد'})
 const [sick,setSick]=useState({employeeId:employees[0]?.id||0,from:today(),to:today(),reason:'',status:'معتمد'})
 const emp=(id:number)=>employees.find(e=>e.id===id)
 function saveTreatment(){if(!form.employeeId||!form.medicine.trim())return alert('اختر الموظف واكتب العلاج');setTreatmentRequests(x=>[...x,{...form,id:uid()}]);setOpen('');setForm({...form,medicine:'',quantity:'',notes:''})}
 function saveSick(){if(!sick.employeeId||sick.to<sick.from)return alert('راجع الموظف والتاريخ');setMedicalLeaves(x=>[...x,{...sick,id:uid(),days:days(sick.from,sick.to)}]);setOpen('')}
 function printPreview(){setTimeout(()=>window.print(),100)}
 const active=medicalLeaves.filter(x=>x.status!=='مرفوض'&&x.to>=today()),pending=treatmentRequests.filter(x=>x.status!=='مكتمل'),valid=treatmentDecisions.filter(x=>x.status==='ساري'&&x.startDate<=today()&&x.endDate>=today())
 return <div className="medical-enhanced"><section className="page-actions"><div><h2>الخدمات الطبية</h2><p>الكشف الطبي، العلاج، الإجازات المرضية، قرارات العلاج والتأمين في ملف واحد.</p></div><div className="actions"><button className="view-btn" onClick={()=>setOpen('sick')}>＋ إجازة مرضية</button><button className="primary-btn" onClick={()=>setOpen('treatment')}>＋ طلب علاج</button></div></section>
 <section className="stats"><div className="stat-card"><div className="stat-icon">💊</div><div><span>طلبات علاج</span><strong>{treatmentRequests.length}</strong></div></div><div className="stat-card"><div className="stat-icon">🩺</div><div><span>إجازات مرضية</span><strong>{medicalLeaves.length}</strong></div></div><div className="stat-card"><div className="stat-icon">📜</div><div><span>قرارات سارية</span><strong>{valid.length}</strong></div></div><div className="stat-card"><div className="stat-icon">⏳</div><div><span>طلبات معلقة</span><strong>{pending.length}</strong></div></div></section>
 <div className="tabs medical-tabs">{[['overview','نظرة عامة'],['treatment','طلبات العلاج'],['sick','الإجازات المرضية'],['decisions','قرارات العلاج'],['records','الملف الطبي']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
 {tab==='overview'&&<section className="panel"><div className="medical-mini"><div><span>إجازات مرضية نشطة</span><strong>{active.length}</strong></div><div><span>طلبات علاج مفتوحة</span><strong>{pending.length}</strong></div><div><span>قرارات سارية</span><strong>{valid.length}</strong></div><div><span>فحوصات</span><strong>{medicalExams.length}</strong></div></div><div className="quick-actions"><button onClick={()=>setOpen('treatment')}>💊 إنشاء طلب علاج</button><button onClick={()=>setOpen('sick')}>🩺 تسجيل إجازة مرضية</button><button onClick={()=>setTab('decisions')}>📜 متابعة قرارات العلاج</button></div></section>}
 {tab==='treatment'&&<section className="panel table-panel"><div className="panel-header"><h3>طلبات العلاج</h3><button className="primary-btn" onClick={()=>setOpen('treatment')}>＋ طلب علاج</button></div><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>التاريخ</th><th>العلاج</th><th>الكمية</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{treatmentRequests.map(r=><tr key={r.id}><td>{emp(r.employeeId)?.name||'—'}</td><td>{r.date}</td><td>{r.medicine}</td><td>{r.quantity||'—'}</td><td>{r.status}</td><td><button className="view-btn" onClick={()=>setPreview(r)}>👁 النموذج</button> <button className="view-btn" onClick={()=>setTreatmentRequests(xs=>xs.map(x=>x.id===r.id?{...x,status:x.status==='مكتمل'?'جديد':'مكتمل'}:x))}>تحديث</button><button className="danger-btn" onClick={()=>setTreatmentRequests(xs=>xs.filter(x=>x.id!==r.id))}>حذف</button></td></tr>)}</tbody></table></div></section>}
 {tab==='sick'&&<section className="panel table-panel"><div className="panel-header"><h3>الإجازات المرضية</h3><button className="primary-btn" onClick={()=>setOpen('sick')}>＋ إجازة مرضية</button></div><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>من</th><th>إلى</th><th>الأيام</th><th>السبب</th><th>الحالة</th></tr></thead><tbody>{medicalLeaves.map(r=><tr key={r.id}><td>{emp(r.employeeId)?.name||'—'}</td><td>{r.from}</td><td>{r.to}</td><td>{r.days}</td><td>{r.reason}</td><td>{r.status}</td></tr>)}</tbody></table></div></section>}
 {tab==='decisions'&&<section className="panel table-panel"><div className="panel-header"><h3>قرارات العلاج</h3><p>يمكن متابعة القرار والصرف الشهري من نفس شاشة الموظف.</p></div><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>رقم القرار</th><th>من</th><th>إلى</th><th>العلاج الشهري</th><th>الحالة</th></tr></thead><tbody>{treatmentDecisions.map(r=><tr key={r.id}><td>{emp(r.employeeId)?.name||'—'}</td><td>{r.decisionNo}</td><td>{r.startDate}</td><td>{r.endDate}</td><td>{r.monthlyTreatment}</td><td>{r.status}</td></tr>)}</tbody></table></div></section>}
 {tab==='records'&&<section className="panel table-panel"><div className="panel-header"><h3>الملف الطبي</h3></div><div className="table-wrap"><table><thead><tr><th>الموظف</th><th>نوع الخدمة</th><th>التاريخ</th><th>النتيجة</th><th>الطبيب</th></tr></thead><tbody>{medicalExams.map(r=><tr key={r.id}><td>{emp(r.employeeId)?.name||'—'}</td><td>{r.type}</td><td>{r.date}</td><td>{r.result}</td><td>{r.doctor}</td></tr>)}</tbody></table></div></section>}
 {open==='treatment'&&<div className="modal-backdrop"><div className="modal wide-modal"><div className="modal-head"><h2>طلب علاج</h2><button onClick={()=>setOpen('')}>×</button></div><div className="form-grid"><label>الموظف<select value={form.employeeId} onChange={e=>setForm(x=>({...x,employeeId:+e.target.value}))}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.code}</option>)}</select></label><label>التاريخ<input type="date" value={form.date} onChange={e=>setForm(x=>({...x,date:e.target.value}))}/></label><label>العلاج / الدواء<input value={form.medicine} onChange={e=>setForm(x=>({...x,medicine:e.target.value}))}/></label><label>الكمية<input value={form.quantity} onChange={e=>setForm(x=>({...x,quantity:e.target.value}))}/></label><label>الجهة الطبية<input value={form.provider} onChange={e=>setForm(x=>({...x,provider:e.target.value}))}/></label><label className="full">ملاحظات<textarea value={form.notes} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label></div><button className="primary-btn" onClick={saveTreatment}>💾 حفظ وإظهار النموذج</button></div></div>}
 {open==='sick'&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>تسجيل إجازة مرضية</h2><button onClick={()=>setOpen('')}>×</button></div><div className="form-grid"><label>الموظف<select value={sick.employeeId} onChange={e=>setSick(x=>({...x,employeeId:+e.target.value}))}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.code}</option>)}</select></label><label>من<input type="date" value={sick.from} onChange={e=>setSick(x=>({...x,from:e.target.value}))}/></label><label>إلى<input type="date" value={sick.to} onChange={e=>setSick(x=>({...x,to:e.target.value}))}/></label><label className="full">سبب المرض / التشخيص<textarea value={sick.reason} onChange={e=>setSick(x=>({...x,reason:e.target.value}))}/></label></div><button className="primary-btn" onClick={saveSick}>💾 حفظ الإجازة</button></div></div>}
 {preview&&<div className="modal-backdrop"><div className="modal wide-modal"><div className="modal-head"><h2>معاينة نموذج طلب العلاج</h2><button onClick={()=>setPreview(null)}>×</button></div><div className="official-form treatment-official"><div className="official-head"><div><strong>شركة مصر الوسطى لتوزيع الكهرباء</strong><span>قطاع بني سويف</span><span>الإدارة العامة __________________</span></div><div className="form-number">طلب علاج</div></div><h1>نموذج طلب علاج</h1><div className="official-fields"><div><b>اسم الموظف</b><span>{emp(preview.employeeId)?.name||''}</span></div><div><b>الرقم الوظيفي</b><span>{emp(preview.employeeId)?.code||''}</span></div><div><b>الرقم القومي</b><span>{emp(preview.employeeId)?.nationalId||''}</span></div><div><b>الوظيفة</b><span>{emp(preview.employeeId)?.job||''}</span></div><div><b>التاريخ</b><span>{preview.date}</span></div><div><b>العلاج</b><span>{preview.medicine}</span></div><div><b>الكمية</b><span>{preview.quantity||'—'}</span></div><div className="full"><b>الجهة الطبية</b><span>{preview.provider||'—'}</span></div><div className="full"><b>ملاحظات</b><span>{preview.notes||'—'}</span></div></div><div className="official-approval"><table><tbody><tr><th>اعتماد المدير المختص</th><th>قسم الخدمات الطبية</th></tr><tr><td style={{height:80}}></td><td></td></tr></tbody></table></div></div><div className="print-toolbar"><button className="primary-btn" onClick={printPreview}>🖨️ طباعة</button><button className="secondary-btn" onClick={()=>setPreview(null)}>إغلاق</button></div></div></div>}
 </div>
}
